### ISSUE TITLE
[delete]

### ISSUE THREAD

**Issue by celsomtrindade** [taianunes/woocommerce-asaas#2]
[delete]

**Comment by taianunes** [comment]
Celso, 

O desenvolvimento desse plugin nunca foi finalizado. Se tiver interesse em continuar esse trabalho, posso passar esse repositório para seu nome.

**Comment by celsomtrindade** [comment]
Não é o plugin oficial? Pois vi que o que encontramos no wordpress foi atualizado faz 2 meses (mas contem alguns 'poréns').

**Comment by taianunes** [comment]
@celsomtrindade, infelizmente não. Foi um projeto que não dei sequencia e nesse meio tempo o próprio dono do produto fez a criação do [plugin](https://br.wordpress.org/plugins/woo-asaas/#description). Para não gerar mais confusão, vou encerrar esse projeto, pois não faz mais sentido. 

Procurei pelo repositório oficial do plugin mais não encontrei, talves não esteja no Github. Recomendo que entre em contato através da página de suporte do plugin no WordPress.

Um abraço.
